language: csharp
sudo: required
dotnet: 2.0.0
dist: trusty
install:
  - dotnet restore
  - dotnet nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script: 
  - dotnet build
  - dotnet test