language: csharp
sudo: required
dotnet: 2.0.0
dist: trusty
install:
  - nuget update Neo.Lux.sln
  - nuget install NUnit.Runners -Version 3.2.0 -OutputDirectory testrunner
script: 
  - dotnet restore
  - dotnet build
  - mono ./testrunner/NUnit.ConsoleRunner.3.2.0/tools/nunit3-console.exe ./Neo.Lux.Tests/bin/Release/Neo.Lux.Tests.dll 