language: csharp
sudo: required
mono: 5.2.0
dotnet: 2.0.0
dist: trusty
install:
  - ls $(dirname $(which mono))/../lib/mono/4.6.1/
  - export FrameworkPathOverride=$(dirname $(which mono))/../lib/mono/4.6.1/
  - dotnet restore
script: 
  - dotnet build
  - dotnet test